### ISSUE TITLE
Infinite redirect loop with basic docker setup

### ISSUE THREAD

**Issue by danbo** [keycloak/keycloak-gatekeeper#308]
Been trying to play with keycloak + proxy in docker and am running into this snag :/

Here's my docker-compose.yml

```
version: '3'

networks:
  keycloak-network:

services:

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - keycloak-network
    links:
      - postgres
    ports:
      - "7080:8080"
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"

      POSTGRES_DATABASE: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "password"
      POSTGRES_PORT_5432_TCP_ADDR: "postgres"
      POSTGRES_PORT_5432_TCP_PORT: 5432

  postgres:
    image: postgres:9.6-alpine
    container_name: keycloak_postgres
    restart: unless-stopped
    networks:
      - keycloak-network
    volumes:
      - ./keycloak-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "password"

  keycloak-proxy:
    image: quay.io/gambol99/keycloak-proxy
    container_name: keycloak-proxy
    depends_on:
      - keycloak
    networks:
      - keycloak-network
    ports:
     - "6080:80"
     - "6443:6443"
    volumes:
     - ./config.yml:/opt/config.yml:ro
     - ./ssl:/ssl:ro
    entrypoint: ["/opt/keycloak-proxy", "--config", "/opt/config.yml"]
```

Here's my config.yml that's fed into ketcloak-proxy:
```
verbose: true
secure-cookie: false

discovery-url: http://server:7080/auth/realms/master
listen: 0.0.0.0:80
#redirection-url: http://127.0.0.1:80
upstream-url: http://10.10.0.5:80

client-id: testClient
client-secret: testClient

resources:
- uri: /status-devices.asp
```

Here's the successful startup of keycloak-proxy:
```
keycloak-proxy    | 1.5172872957784212e+09      info    keycloak-proxy/server.go:644    successfully retrieved openid configuration from the discovery
keycloak-proxy    | 1.5172872957902608e+09      info    keycloak-proxy/server.go:151    enabled reverse proxy mode, upstream url        {"url": "http://10.10.0.5:80"}
keycloak-proxy    | 1.5172872957905526e+09      info    keycloak-proxy/server.go:224    protecting resource     {"resource": "uri: /status-devices.asp, methods: DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT,TRACE, required: authentication only"}
keycloak-proxy    | 1.517287295790631e+09       warn    keycloak-proxy/server.go:243    no redirection url has been set, will use host headers
keycloak-proxy    | 1.5172872957913888e+09      info    keycloak-proxy/server.go:345    keycloak proxy service starting {"interface": "0.0.0.0:80"}
```
I hit the upstream URL at / and i'm allowed in without auth (as expected)

I hit the /status-devices.asp page, get the login page, log in and then I get 

```
keycloak-proxy    | 1.5172873101173725e+09      error   keycloak-proxy/middleware.go:110        no session found in request, redirecting for authorization      {"error": "malformed JWS, only 1 segments"}
keycloak-proxy    | 1.5172873101296835e+09      debug   keycloak-proxy/handlers.go:80   incoming authorization request from client address      {"access_type": "", "auth_url": "http://server:7080/auth/realms/master/protocol/openid-connect/auth?client_id=testClient&redirect_uri=http%3A%2F%2Fserver%3A6080%2Foauth%2Fcallback&response_type=code&scope=openid+email+profile&state=L3N0YXR1cy1kZXZpY2VzLmFzcA%3D%3D", "client_ip": "10.10.0.30:52206"}
keycloak-proxy    | 1.5172873151822534e+09      info    keycloak-proxy/handlers.go:159  issuing access token for user   {"email": "", "expires": "2018-01-30T04:42:55Z", "duration": "59.817748704s"}
keycloak-proxy    | 1.5172873151894944e+09      error   keycloak-proxy/middleware.go:110        no session found in request, redirecting for authorization      {"error": "malformed JWS, only 1 segments"}
keycloak-proxy    | 1.5172873151966324e+09      debug   keycloak-proxy/handlers.go:80   incoming authorization request from client address      {"access_type": "", "auth_url": "http://server:7080/auth/realms/master/protocol/openid-connect/auth?client_id=testClient&redirect_uri=http%3A%2F%2Fserver%3A6080%2Foauth%2Fcallback&response_type=code&scope=openid+email+profile&state=L3N0YXR1cy1kZXZpY2VzLmFzcA%3D%3D", "client_ip": "10.10.0.30:52206"}
keycloak-proxy    | 1.517287315302124e+09       info    keycloak-proxy/handlers.go:159  issuing access token for user   {"email": "", "expires": "2018-01-30T04:42:55Z", "duration": "59.697879001s"}
keycloak-proxy    | 1.5172873153103437e+09      error   keycloak-proxy/middleware.go:110        no session found in request, redirecting for authorization      {"error": "malformed JWS, only 1 segments"}
keycloak-proxy    | 1.517287315317877e+09       debug   keycloak-proxy/handlers.go:80   incoming authorization request from client address      {"access_type": "", "auth_url": "http://server:7080/auth/realms/master/protocol/openid-connect/auth?client_id=testClient&redirect_uri=http%3A%2F%2Fserver%3A6080%2Foauth%2Fcallback&response_type=code&scope=openid+email+profile&state=L3N0YXR1cy1kZXZpY2VzLmFzcA%3D%3D", "client_ip": "10.10.0.30:52206"}
keycloak-proxy    | 1.517287315411422e+09       info    keycloak-proxy/handlers.go:159  issuing access token for user   {"email": "", "expires": "2018-01-30T04:42:55Z", "duration": "59.58858209s"}
keycloak-proxy    | 1.5172873154191618e+09      error   keycloak-proxy/middleware.go:110        no session found in request, redirecting for authorization      {"error": "malformed JWS, only 1 segments"}
keycloak-proxy    | 1.5172873154266746e+09      debug   keycloak-proxy/handlers.go:80   incoming authorization request from client address      {"access_type": "", "auth_url": "http://server:7080/auth/realms/master/protocol/openid-connect/auth?client_id=testClient&redirect_uri=http%3A%2F%2Fserver%3A6080%2Foauth%2Fcallback&response_type=code&scope=openid+email+profile&state=L3N0YXR1cy1kZXZpY2VzLmFzcA%3D%3D", "client_ip": "10.10.0.30:52206"}
keycloak-proxy    | 1.517287315558797e+09       info    keycloak-proxy/handlers.go:159  issuing access token for user   {"email": "", "expires": "2018-01-30T04:42:55Z", "duration": "59.441209006s"}
keycloak-proxy    | 1.5172873155667815e+09      error   keycloak-proxy/middleware.go:110        no session found in request, redirecting for authorization      {"error": "malformed JWS, only 1 segments"}
keycloak-proxy    | 1.517287315572625e+09       debug   keycloak-proxy/handlers.go:80   incoming authorization request from client address      {"access_type": "", "auth_url": "http://server:7080/auth/realms/master/protocol/openid-connect/auth?client_id=testClient&redirect_uri=http%3A%2F%2Fserver%3A6080%2Foauth%2Fcallback&response_type=code&scope=openid+email+profile&state=L3N0YXR1cy1kZXZpY2VzLmFzcA%3D%3D", "client_ip": "10.10.0.30:52206"}
keycloak-proxy    | 1.517287315670206e+09       info    keycloak-proxy/handlers.go:159  issuing access token for user   {"email": "", "expires": "2018-01-30T04:42:55Z", "duration": "59.329799003s"}
keycloak-proxy    | 1.5172873156792266e+09      error   keycloak-proxy/middleware.go:110        no session found in request, redirecting for authorization      {"error": "malformed JWS, only 1 segments"}
keycloak-proxy    | 1.5172873156860926e+09      debug   keycloak-proxy/handlers.go:80   incoming authorization request from client address      {"access_type": "", "auth_url": "http://server:7080/auth/realms/master/protocol/openid-connect/auth?client_id=testClient&redirect_uri=http%3A%2F%2Fserver%3A6080%2Foauth%2Fcallback&response_type=code&scope=openid+email+profile&state=L3N0YXR1cy1kZXZpY2VzLmFzcA%3D%3D", "client_ip": "10.10.0.30:52206"}
```

At which point the browser gives up.

Yes, secure-cookie was set to false.
