### ISSUE TITLE
Redirection URL doesn't work

### ISSUE THREAD

**Issue by waseem-h** [keycloak/keycloak-gatekeeper#331]
Hi, i've been using your keycloak-proxy for a while now and i'm facing a minor issue. Basically I have your proxy running as a sidecar container with an app on kubernetes. The issue is that the app itself is on someurl.com/app and whenever i visit the url, it takes me to keycloak, but the redirect_url in the browser url shows "'someurl.com" instead of someurl.com/app. So after logging in I am redirected to someurl.com which is weird

i've tried passing the argument `redirection-url=/app` but it doesn't work as well. Here's my config

```yaml
client-id: <client-id>
client-secret: <client-secret>
discovery-url: https://<keycloak-url>/auth/realms/<realm>
enable-default-deny: true
listen: 0.0.0.0:80
upstream-url: http://127.0.0.1:5601
redirection-url: /kibana
secure-cookie: false
verbose: true
enable-logging: true
cors-origins:
- '*'
cors-methods:
- GET
- POST
resources:
- uri: /

```
