### ISSUE TITLE
Support mapping additional request paths to different upstream URLs.

### ISSUE THREAD

**Issue by chirino** [keycloak/keycloak-gatekeeper#524]
Currently the configuration only supports specifying one upstream URL.. This works if your only proxying to a single upstream service:

```yaml
# the upstream endpoint which we should proxy request
upstream-url: http://myapp:80
resources:
- uri: /
  roles:
  - user
- uri: /admin
  roles:
  - admin
```

But sometimes, apps built in a micro service style are are composed of multiple services routed to by path.  For example: `http://myapp-admin/admin` and `http://myapp-user/` could be two different independently scaled services in the app built by different groups, but should composed into a single URL namespace.

I propose that the configuration also support the following:

```yaml
# the upstream endpoint which we should proxy request
upstream-url: http://myapp-user:80 # The default upstream if a better match is not found:
upstream-url-paths: 
- uri: /admin
  upstream-url:  http://myapp-admin:80
- uri: /data
  upstream-url:  http://myapp-data:80
resources:
- uri: /
  roles:
  - user
- uri: /admin
  roles:
  - admin
```
