### ISSUE TITLE
no session found in request, redirecting for authorization

### ISSUE THREAD

**Issue by pop654123** [keycloak/keycloak-gatekeeper#529]
Gatekeeper work as proxy for Kibana，

**Comment by abstractj** [comment]
@pop654123 could you please provide more details like:

- [ ] YAML file for Louketo configuration
- [ ] JSON file with your client configuration
- [ ] Version of the Keycloak server

**Comment by wenerme** [comment]
Keycloak 10.0.2

```
starting the service	{"prog": "louketo-proxy", "author": "Louketo", "version": "v2.3.0 (git+sha: aa9ae98-dirty, built: 15-06-2020)"}
no session found in request, redirecting for authorization	{"error": "authentication session not found"}
```


args

```
- '--listen=0.0.0.0:3000'
- '--discovery-url=https://xxxx/auth/realms/xxxxx'
- '--client-id=gatekeeper'
- '--client-secret=xxxx'
- '--upstream-url=http://xxxx:9000'
- '--resources=uri=/|white-listed=true'
- '--resources=uri=/favicon|white-listed=true'
- '--resources=uri=/css/*|white-listed=true'
- '--resources=uri=/img/*|white-listed=true'
- '--resources=uri=/public/*|white-listed=true'
```

**Comment by borisovj** [comment]
Hello got the same issue:

Keycloak 10.0.2

          args:
            - --listen=0.0.0.0:10000
            - --discovery-url=https://<keycloakpage>/auth/realms/<myrealm>
            - --client-id=<myrealm>
            - --client-secret=xxx
            - --secure-cookie=false
            - --encryption-key=xxx
            - --enable-refresh-tokens=true
            - --enable-default-deny=false
            - --enable-json-logging=true
            - --enable-logging=true
            - --enable-request-id=true
            - --skip-openid-provider-tls-verify=true
            - --upstream-url=http://127.0.0.1:5601
            - --resources=uri=/*|groups=LoggingUsers,LoggingAdmins
            - --verbose=false
            - --enable-authorization-header=false
            - --enable-authorization-cookies=false
            - --enable-token-header=false
            - --enable-logout-redirect=true
            - --redirection-url=https://<kibana>
            - --revocation-url=https://<keycloak>
            - --openid-provider-timeout=120s
            - --upstream-timeout=120s
            - --upstream-keepalive-timeout=120s
            - --upstream-tls-handshake-timeout=120s
            - --upstream-response-header-timeout=120s
            - --upstream-expect-continue-timeout=120s
            - --server-read-timeout=120s
            - --server-write-timeout=120s
            - --server-idle-timeout=120s

**Comment by tobiasbenkner** [comment]
same here

```
./bin/keycloak-gatekeeper \
  --encryption-key=yyy \
  --listen=0.0.0.0:3006 \
  --discovery-url=https://xxx/auth/realms/dev \
  --client-id=backend-client \
  --client-secret=23232323 \
  --enable-refresh-tokens=true \
  --base-uri=/ \
  --upstream-url=http://127.0.0.1:3001 \
  --no-redirects=true \
  --resources="uri=/api/auth/login|white-listed=true" \
  --resources="uri=/api/*|require-any-role=true" \
  --add-claims=app-id
```

**Comment by petrkalina** [comment]
same problem here - i.,e. works with older keycloak-gatekeeper versions (verified 6.0.1), but not with newest (checked 9.0.0 and 10.0.1).

conf - using docker image with:

```
                env:
                    TZ: Europe/Tallinn
                    PROXY_LISTEN: 0.0.0.0:8243
                    PROXY_REDIRECTION_URL: https://demologging1tln.vna.pacs.ee:8243
                    PROXY_UPSTREAM_URL: http://elasticsearch:9200
                    PROXY_DISCOVERY_URL: https://demoauthvip1.vna.pacs.ee:8843/auth/realms/dcm4che
                    PROXY_CLIENT_ID: arr-gatekeeper
                    PROXY_CLIENT_SECRET: {secret}
                    PROXY_ENCRYPTION_KEY: AgXa7xRcoClDEU0ZDSH4X0XhL5Qy2Z2j
                command:
                    - "--openid-provider-timeout=120s"
                    - "--tls-cert=/ssl/demologging1tln.vna.pacs.ee.crt"
                    - "--tls-private-key=/ssl/demologging1tln.vna.pacs.ee.key"
                    - "--skip-openid-provider-tls-verify=true"
                    - "--enable-refresh-tokens=true"
                    - "--resources=uri=/*|methods=GET|roles=auditlog"
```

the code that fails in 10.0.1 is:

```
auth_rsp=`curl -k --data "grant_type=client_credentials&client_id=${client_id}&client_secret=${client_secret}" "${auth_url}/auth/realms/dcm4che/protocol/openid-connect/token"`
token=`echo ${auth_rsp} | sed 's/.*access_token":"//g' | sed 's/".*//g'`
curl -v -k  -H "Authorization: bearer ${token}" https://demologging1tln.vna.pacs.ee:8243
```

.. same code runs well in 6.0.1 gatekeeper..
